In [1]:
import pandas as pd
pd.__version__

'0.24.0.dev0+757.ge8d29e73e'

### Why do we care?

In [2]:
s = Series([1, 2, 3])
s

0    1
1    2
2    3
dtype: int64

In [3]:
s.reindex([1, 2, 3])

1    2.0
2    3.0
3    NaN
dtype: float64

In [4]:
s = Series([1, 2, 3], dtype='Int64')
s

0    1
1    2
2    3
dtype: Int64

In [5]:
rs = s.reindex([1, 2, 3])
rs

1      2
2      3
3    NaN
dtype: Int64

### Operations

In [6]:
rs.sum()

5

In [7]:
df = pd.DataFrame({'Int': s, 'int': [1, 2, 1]})
df

Int  int
0   1    1
1   2    2
2   3    1

In [8]:
df.dtypes

Int    Int64
int    int64
dtype: object

In [9]:
df.groupby('int').Int.sum()

int
1    4
2    2
Name: Int, dtype: int64

In [10]:
df + 1

Int  int
0   2    2
1   3    3
2   4    2

In [11]:
df.loc[2] = np.nan

In [12]:
df

Int  int
0    1  1.0
1    2  2.0
2  NaN  NaN

In [13]:
df.fillna(0)

Int  int
0   1  1.0
1   2  2.0
2   0  0.0

In [14]:
df.fillna(0).dtypes

Int      Int64
int    float64
dtype: object

In [15]:
df[df.Int.isin([2])]

Int  int
1   2  2.0

### Implementation

In [16]:
s = df['Int']
s

0      1
1      2
2    NaN
Name: Int, dtype: Int64

In [17]:
s.values

IntegerArray([1, 2, nan], dtype='Int64')

In [18]:
s.values._data

array([1, 2, 1])

In [19]:
s.values._mask

array([False, False,  True])

In [20]:
s.nbytes

27

In [21]:
s.values._data.nbytes

24

In [22]:
s.values._mask.nbytes

3

### Interface

In [23]:
s.values.dropna()

IntegerArray([1, 2], dtype='Int64')

In [24]:
s.values.factorize()

(array([ 0,  1, -1]), IntegerArray([1, 2], dtype='Int64'))

In [25]:
s.values.isna()

array([False, False,  True])

In [26]:
s.values.take([0, 1, 2])

IntegerArray([1, 2, nan], dtype='Int64')

In [27]:
s.values.unique()

IntegerArray([1, 2, nan], dtype='Int64')